namespace CsvReaderApp.Binance.Models
{
    public enum OperationEnum
    {
        //2021
        Deposit,
        Transaction_Related,
        Large_OTC_trading,
        Super_BNB_Mining,
        POS_savings_purchase,
        Buy,
        Fee,
        Referral_Kickback,
        Launchpool_Interest,
        POS_savings_interest,
        POS_savings_redemption,
        Sell,
        ETH_Staking,
        ETH_Staking_Reward,
        Savings_purchase,
        Savings_Interest,
        Savings_Principal_redemption,
        //2022
        Transaction_Buy,
        Transaction_Spend,
        Referral_Commission,
        Transaction_Revenue,
        Transaction_Sold
    }
}
